### ISSUE TITLE
TclError: bad row value "0.0"

### ISSUE THREAD

**Issue by madnesso** [kidddw/Item-Build-Prescriber-for-Dota-2#1]
when I run _gui using anaconda spyder i get this 

`n [1]: runfile('C:/Users/madnesso/Desktop/Item-Build-Prescriber-for-Dota-2-master/Item-Build-Prescriber-for-Dota-2-master/Dota_item_prescriber_gui.py', wdir='C:/Users/madnesso/Desktop/Item-Build-Prescriber-for-Dota-2-master/Item-Build-Prescriber-for-Dota-2-master')
C:/Users/madnesso/Desktop/Item-Build-Prescriber-for-Dota-2-master/Item-Build-Prescriber-for-Dota-2-master/Dota_item_prescriber_gui.py:64: DeprecationWarning: 'U' mode is deprecated
  f = open(file_name, 'rU')
Traceback (most recent call last):

  File "<ipython-input-1-301142c33d7e>", line 1, in <module>
    runfile('C:/Users/madnesso/Desktop/Item-Build-Prescriber-for-Dota-2-master/Item-Build-Prescriber-for-Dota-2-master/Dota_item_prescriber_gui.py', wdir='C:/Users/madnesso/Desktop/Item-Build-Prescriber-for-Dota-2-master/Item-Build-Prescriber-for-Dota-2-master')

  File "C:\Users\madnesso\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\madnesso\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/madnesso/Desktop/Item-Build-Prescriber-for-Dota-2-master/Item-Build-Prescriber-for-Dota-2-master/Dota_item_prescriber_gui.py", line 255, in <module>
    my_gui = MyFirstGUI(root)

  File "C:/Users/madnesso/Desktop/Item-Build-Prescriber-for-Dota-2-master/Item-Build-Prescriber-for-Dota-2-master/Dota_item_prescriber_gui.py", line 138, in __init__
    self.hero_buttons[-1].grid(row=row_index, column=col_index, padx=2, pady=2)

  File "C:\Users\madnesso\Anaconda3\lib\tkinter\__init__.py", line 2221, in grid_configure
    + self._options(cnf, kw))

TclError: bad row value "0.0": must be a non-negative integer`

**Comment by madnesso** [comment]
nvm fixed with using anaconda version v2.7
